#! /bin/sh

### AUTOSTART ####
$HOME/.screenlayout/setres.sh &
$HOME/.config/polybar/launch.sh &
nm-applet &
nitrogen --restore &
sxhkd &

### MONITORS ####
bspc monitor -d I II III IV V VI VII VIII IX X

### BSPWM COLORS ###
bspc config normal_border_color     '#c0c0c0'
bspc config active_border_color     '#008000'
bspc config focused_border_color    '#008000'
bspc config presel_feedback_color   '#800000'

### BSPWM CONFIG ###
bspc config border_radius        5
bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio       0.50
bspc config top_padding         25
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config single_monocle         false
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config click_to_focus           any
bspc config swallow_first_click     true
bspc config focus_follows_pointer   true

bspc config pointer_modifier             mod4
bspc config pointer_action1              move
bspc config pointer_action2       resize_side
bspc config pointer_action3     resize_corner

### MISC from Example ###
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

