#!/bin/zsh
#
backupFile=$HOME/$(date +'%Y%m%d-'$(hostname --short)'-backup.tar.gz')

tar --exclude="*.tar.gz" --exclude "*tar" --exclude="*.iso" -czvf $backupFile \
$HOME/libvirt $HOME/OCP /etc/named* /etc/hosts

if [ -d /mnt/perl ]; then
  mv $backupFile /mnt/perl
fi
